--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: apacjhe2
  name: webapp1-svc
spec: 
  ports: 
    - 
      nodePort: 30081
      port: 80
  selector: 
    app: httpd
  type: NodePort

